apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lemonbox
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  namespace: default
spec:
  rules:
    - host: ip-172-31-26-49.cn-northwest-1.compute.internal
      http:
        paths:
          - path: /java(/|$)(.*)
            backend:
              serviceName: stress-java
              servicePort: 8080
    - host: ip-172-31-26-49.cn-northwest-1.compute.internal
      http:
        paths:
          - path: /node(/|$)(.*)
            backend:
              serviceName: stress-node
              servicePort: 3000

